### ISSUE TITLE
Cannot find module @pact-foundation/pact-node

### ISSUE THREAD

**Issue by hemantp2001** [DiUS/pact-workshop-js#1]
I thought this issue was fixed. As in another post I see its already added as a direct dependency:

When I fire npm run "test:pact:consumer"  I am getting below error:

Error: Cannot find module '@pact-foundation/pact-node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\userid\pact-workshop-js\node_modules\pact\sr
c\dsl\verifier.js:8:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by mefellows** [comment]
This should be fixed in the latest edition, as it's a dependency in the root package. Please re-test, and let us know if you're still having any issues.
